name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Запускается ежедневно в полночь UTC
  workflow_dispatch: # Позволяет запустить вручную

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Gagabooga3000
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: output

